# Generated by Django 5.0 on 2024-07-07 07:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_checkemail_code_alter_usermodel_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="is_employee",
        ),
    ]
